[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist/frontend/browser"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

[[redirects]]
  from = "https://baseline-gearhub.netlify.app/*"
  to = "https://courtgo.club/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
