const mongoose = require("mongoose");

const ratesSchema = new mongoose.Schema({
  clubId: { type: mongoose.Schema.Types.ObjectId, ref: "Club", required: true, unique: true },
  withoutLightRate: { type: Number, required: true, min: 0 },
  lightRate: { type: Number, required: true, min: 0 },
  training2WithoutLightRate: { type: Number, required: true, min: 0 },
  training2LightRate: { type: Number, required: true, min: 0 },
  ballBoyRate: { type: Number, required: true, min: 0 },
  reservationWeekdayRate: { type: Number, default: 0, min: 0 },
  reservationWeekendRate: { type: Number, default: 0, min: 0 },
  reservationHolidayRate: { type: Number, default: 0, min: 0 },
  reservationGuestFee: { type: Number, default: 0, min: 0 },
  reservationGuestFeeThreshold: { type: Number, default: 0, min: 0 },
  perGameFee: { type: Number, default: 0, min: 0 },
  perGameGuestFee: { type: Number, default: 0, min: 0 },
  exclusiveEventEnabled: { type: Boolean, default: false },
  exclusiveEventRate: { type: Number, default: 0, min: 0 },
  exclusiveEventIncludedPax: { type: Number, default: 0, min: 0 },
  exclusiveEventExcessPaxFee: { type: Number, default: 0, min: 0 },
  exclusiveEventMaxPax: { type: Number, default: 0, min: 0 },
  exclusiveEventPolicies: [{ type: String }],
  rentalBalls50Rate: { type: Number, default: 0, min: 0 },
  rentalBalls100Rate: { type: Number, default: 0, min: 0 },
  rentalBallMachineRate: { type: Number, default: 0, min: 0 },
  rentalRacketRate: { type: Number, default: 0, min: 0 },
  coachingEnabled: { type: Boolean, default: false },
  coachingMinHours: { type: Number, default: 2, min: 1 },
  coachingMaxPax: { type: Number, default: 6, min: 1 },
  coachingRate1Pax: { type: Number, default: 0, min: 0 },
  coachingRate2Pax: { type: Number, default: 0, min: 0 },
  coachingRate3to6Pax: { type: Number, default: 0, min: 0 },
  updatedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("Rates", ratesSchema);
